version: '3.8'

services:
  app:
    build:
      # context 路径必须写绝对路径，以便嵌套使用
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 8.1-bullseye
    image: edwinhuish/vscode-php:8.1-20220511
